### ISSUE TITLE
Could not find match

### ISSUE THREAD

**Issue by nthulke** [LukePrior/nbn-service-check#10]
Hello,

It looks like this isnt working at the moment, and having a high level look at your code it appears to be due to the fact that my republic are no longer selling NBN.

![image](https://user-images.githubusercontent.com/69140718/227746574-4180661f-e762-4ef1-ba5d-7a825a436f83.png)

**Comment by LukePrior** [comment]
Hi, that would explain it.

I'll need to investigate potential replacements.

**Comment by nthulke** [comment]
Looking at this one https://github.com/chrishardinge/nbn-lookup/blob/master/src/Search.php it works if I install it locally, so it must be pulling from something that has the data.

**Comment by LukePrior** [comment]
Looking into switching to the Launtel API.

**Comment by LukePrior** [comment]
I have now switched over and it should be working again
