### ISSUE TITLE
Add on generates a new report when navigating through picture gallery

### ISSUE THREAD

**Issue by tabasc** [LukePrior/nbn-service-check#8]
Excellent add on, but if I view pictures, when I exit the gallery the add on will have injected a new NBN report dialog for every time a picture was loaded.

**Comment by LukePrior** [comment]
Hi,

What site is this on?

I will investigate further.

Thanks,
Luke

**Comment by tabasc** [comment]
REIWA site. I also tested with adblocking/privacy extensions disabled in case they were causing it but still happened.

**Comment by LukePrior** [comment]
I have replicated the issue locally and created a fix that seems to be working. I will publish it in the next few days alongside some other changes.

**Comment by tabasc** [comment]
Awesome! Many, many thanks for creating the add on, and addressing this bug so quickly.
